### ISSUE TITLE
Invalid memory comparisons

### ISSUE THREAD

**Issue by stevenjohnstone** [ruby/prism#1612]
3563e5c5d55cb3012336abbff73c0acac820f8f2 changes a number of ```strncmp``` calls to ```memcmp``` and this leads to out-of-bounds memory reads, in particular where ```peek_string``` is used. These are detected during fuzzing and, while probably benign, cause problems with coverage guidance as there are many ways to get essentially the same crash with slightly different inputs.

**Comment by froydnj** [comment]
Do you have examples of these sorts of crashes?

**Comment by stevenjohnstone** [comment]
> Do you have examples of these sorts of crashes?

Aye, here's an example where ```memcmp``` will be used to compare 5 bytes out of bounds:
```
$ echo -n "=" |./build/fuzz.parse -
Reading 1 bytes from -
=================================================================
==159391==ERROR: AddressSanitizer: global-buffer-overflow on address 0x561545705c01 at pc 0x56154575e7c6 bp 0x7ffc19fced20 sp 0x7ffc19fce4d0
READ of size 5 at 0x561545705c01 thread T0
    #0 0x56154575e7c5 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long) crtstuff.c
    #1 0x56154575ecb9 in memcmp (/home/stevie/code/prism/build/fuzz.parse+0xb0cb9) (BuildId: 88df46cf0c232021)
    #2 0x56154580d540 in parser_lex /prism/src/prism.c:6639:62
    #3 0x561545808f27 in parse_program /prism/src/prism.c:14317:5
    #4 0x561545808da2 in pm_parse /prism/src/prism.c:14561:12
    #5 0x56154589ba02 in pm_parse_serialize /prism/src/prism.c:14584:23
    #6 0x5615458bcaf2 in harness /prism/fuzz/parse.c:7:5
    #7 0x5615458bcc2a in LLVMFuzzerTestOneInput /prism/fuzz/fuzz.c:8:5
    #8 0x56154580257d in ExecuteFilesOnyByOne /AFLplusplus/utils/aflpp_driver/aflpp_driver.c:255:7
    #9 0x561545802388 in LLVMFuzzerRunDriver /AFLplusplus/utils/aflpp_driver/aflpp_driver.c
    #10 0x561545801f48 in main /AFLplusplus/utils/aflpp_driver/aflpp_driver.c:300:10
    #11 0x7f639fe29d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #12 0x7f639fe29e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #13 0x561545744264 in _start (/home/stevie/code/prism/build/fuzz.parse+0x96264) (BuildId: 88df46cf0c232021)

0x561545705c01 is located 63 bytes to the left of global variable '<string literal>' defined in 'src/prism.c:14573:34' (0x561545705c40) of size 2
0x561545705c01 is located 31 bytes to the left of global variable '<string literal>' defined in 'src/prism.c:14566:34' (0x561545705c20) of size 6
  '<string literal>' is ascii string 'PRISM'
0x561545705c01 is located 0 bytes to the right of global variable '<string literal>' defined in 'src/prism.c:14418:31' (0x561545705c00) of size 1
  '<string literal>' is ascii string ''
SUMMARY: AddressSanitizer: global-buffer-overflow crtstuff.c in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long)
Shadow bytes around the buggy address:
  0x0ac328ad8b30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ac328ad8b40: 00 00 00 00 00 00 00 00 00 00 00 00 07 f9 f9 f9
  0x0ac328ad8b50: 00 00 07 f9 f9 f9 f9 f9 00 04 f9 f9 00 00 00 00
  0x0ac328ad8b60: 00 00 00 f9 f9 f9 f9 f9 00 04 f9 f9 00 07 f9 f9
  0x0ac328ad8b70: 00 00 00 00 00 00 00 00 00 02 f9 f9 f9 f9 f9 f9
=>0x0ac328ad8b80:[01]f9 f9 f9 06 f9 f9 f9 02 f9 f9 f9 00 04 f9 f9
  0x0ac328ad8b90: 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 00 00 00 00
  0x0ac328ad8ba0: 03 f9 f9 f9 f9 f9 f9 f9 00 00 00 07 f9 f9 f9 f9
  0x0ac328ad8bb0: 06 f9 f9 f9 00 f9 f9 f9 00 00 00 00 00 05 f9 f9
  0x0ac328ad8bc0: f9 f9 f9 f9 00 00 00 00 00 07 f9 f9 f9 f9 f9 f9
  0x0ac328ad8bd0: 04 f9 f9 f9 00 01 f9 f9 06 f9 f9 f9 06 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==159391==ABORTING
```

**Comment by froydnj** [comment]
That looks more like a case where the return value from `peek_string` is not being correctly checked:

https://github.com/ruby/prism/blob/c8ea6f24e228391a2bf384d7fa57188456eef8aa/src/prism.c#L5020-L5029

whereas here we just use the return unconditionally:

https://github.com/ruby/prism/blob/c8ea6f24e228391a2bf384d7fa57188456eef8aa/src/prism.c#L6639

I don't think this is a `memcmp` vs. `strcmp` issue.

**Comment by stevenjohnstone** [comment]
With this patch
```diff
diff --git a/src/prism.c b/src/prism.c
index f8c0beb3..0772fb23 100644
--- a/src/prism.c
+++ b/src/prism.c
@@ -6636,7 +6636,7 @@ parser_lex(pm_parser_t *parser) {
 
                 // = => =~ == === =begin
                 case '=':
-                    if (current_token_starts_line(parser) && memcmp(peek_string(parser, 5), "begin", 5) == 0 && pm_char_is_whitespace(peek_offset(parser, 5))) {
+                    if (current_token_starts_line(parser) && strncmp((const char *)peek_string(parser, 5), "begin", 5) == 0 && pm_char_is_whitespace(peek_offset(parser, 5))) {
                         pm_token_type_t type = lex_embdoc(parser);
 
                         if (type == PM_TOKEN_EOF) {
```
all the crashing test cases are "fixed". FWIW, I'm not a fan of using C strings anywhere; it'd be better to pass around a pointer and a length (like a golang slice or similar).
