### ISSUE TITLE
`1.method` raises `NotImplemented` when using `Prism::RipperCompat.sexp_raw`

### ISSUE THREAD

**Issue by jtarchie** [ruby/prism#2089]
It appears that there maybe a condition not met for simple sexp example:

```ruby
Prism::RipperCompat.sexp_raw("1.method")
```

raises

```
/opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/ripper_compat.rb:118:in `visit_call_node': NotImplementedError (NotImplementedError)
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/node.rb:2197:in `accept'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/visitor.rb:27:in `block in visit_child_nodes'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/visitor.rb:27:in `each'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/visitor.rb:27:in `visit_child_nodes'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/node.rb:11322:in `accept'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/visitor.rb:17:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/ripper_compat.rb:150:in `block in visit_statements_node'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/ripper_compat.rb:149:in `each'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/ripper_compat.rb:149:in `inject'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/ripper_compat.rb:149:in `visit_statements_node'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/node.rb:15784:in `accept'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/visitor.rb:17:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/ripper_compat.rb:156:in `visit_program_node'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/node.rb:13913:in `accept'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/ripper_compat.rb:101:in `parse'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/prism-0.19.0/lib/prism/ripper_compat.rb:167:in `sexp_raw'
```

To check that this works with Ripper:

```ruby
irb(main):018> Ripper.sexp("1.method")
=>
[:program,
 [[:call, [:@int, "1", [1, 0]], [:@period, ".", [1, 1]], [:@ident, "method", [1, 2]]]]]
```

Haven't investigated the issue. Just reporting since this is a new release.

**Comment by kddnewton** [comment]
Yeah this is a known limitation right now. `RipperCompat.sexp` is definitely not done. Thanks for the report! We're tracking this as a separate project so I'm going to close this one.
