### ISSUE TITLE
Fails to install gem on Windows 11

### ISSUE THREAD

**Issue by iuliu-burtoiu** [ruby/prism#2103]
**Operating System**
```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
```
**Ruby +DevKit**
```
ruby:
  path: C:/tools/ruby30
  version: 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
  platform: x64-mingw32
  cc: gcc.exe (Rev2, Built by MSYS2 project) 11.2.0
ruby_installer:
  package_version: 3.0.3-1
  git_commit: 981867a
msys2:
  path: c:\msys64
sh: GNU bash, version 5.2.9(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.22621.2861]
```
Prism fails to install when building native extentions:

```
> gem install prism
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing prism:
        ERROR: Failed to build gem native extension.

    current directory: C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/prism-0.19.0/ext/prism
C:/tools/ruby30/bin/ruby.exe -I C:/tools/ruby30/lib/ruby/3.0.0 -r ./siteconf20231221-29380-17fq2o.rb extconf.rb
checking for prism.h in C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/prism-0.19.0/include... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/tools/ruby30/bin/$(RUBY_BASE_NAME)
C:/tools/ruby30/lib/ruby/3.0.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/tools/ruby30/lib/ruby/3.0.0/mkmf.rb:613:in `try_cpp'
        from C:/tools/ruby30/lib/ruby/3.0.0/mkmf.rb:1177:in `block in find_header'
        from C:/tools/ruby30/lib/ruby/3.0.0/mkmf.rb:971:in `block in checking_for'
        from C:/tools/ruby30/lib/ruby/3.0.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from C:/tools/ruby30/lib/ruby/3.0.0/mkmf.rb:331:in `open'
        from C:/tools/ruby30/lib/ruby/3.0.0/mkmf.rb:361:in `block in postpone'
        from C:/tools/ruby30/lib/ruby/3.0.0/mkmf.rb:331:in `open'
        from C:/tools/ruby30/lib/ruby/3.0.0/mkmf.rb:357:in `postpone'
        from C:/tools/ruby30/lib/ruby/3.0.0/mkmf.rb:970:in `checking_for'
        from C:/tools/ruby30/lib/ruby/3.0.0/mkmf.rb:1176:in `find_header'
        from extconf.rb:62:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/tools/ruby30/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/prism-0.19.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/prism-0.19.0 for inspection.
Results logged to C:/tools/ruby30/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/prism-0.19.0/gem_make.out
```

Content of `C:/tools/ruby30/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/prism-0.19.0/mkmf.log`:

```
"gcc -o conftest.exe -IC:/tools/ruby30/include/ruby-3.0.0/x64-mingw32 -IC:/tools/ruby30/include/ruby-3.0.0/ruby/backward -IC:/tools/ruby30/include/ruby-3.0.0 -I. -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0600 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -O3 -fno-fast-math -fstack-protector-strong conftest.c  -L. -LC:/tools/ruby30/lib -L. -pipe -s -fstack-protector-strong
-m64   -lx64-msvcrt-ruby300  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return !!argv[argc];
8: }
/* end */
```

**Comment by iuliu-burtoiu** [comment]
Note that upon switching to `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]` , gem was successfully installed.

**Comment by kddnewton** [comment]
It's saying `You have to install development tools first.` on the first one, can you try installing other C extension gems on that version of Ruby to see if it is able to install? I'm trying to narrow down if this is just prism or if it's the installation of that version of Ruby on your machine.

**Comment by hsbt** [comment]
I could install `prism` with latest version of `RubyInstaller2` and Windows 11 Pro.

```
PS C:\Users\hsbt> ruby -v
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x64-mingw-ucrt]
PS C:\Users\hsbt> gem -v
3.5.3
PS C:\Users\hsbt> gem i prism
Fetching prism-0.19.0.gem
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed prism-0.19.0
Parsing documentation for prism-0.19.0
Installing ri documentation for prism-0.19.0
Done installing documentation for prism after 31 seconds
1 gem installed
```

**Comment by kddnewton** [comment]
Thanks @hsbt - @iuliu-burtoiu we've not been able to reproduce this, so I'm going to close this for now. If you can reproduce it reliably let me know!

**Comment by dillonbarker-te** [comment]
We have the same error on ruby 3.1.4.

**Comment by kddnewton** [comment]
@dillonbarker-te have you tried the suggested steps of installing other native gems?

**Comment by Tofpu** [comment]
Hey, I'm unable to install prism either, but on Windows 10 instead. Tried installing another native `C` gem, `openssl` and that worked. Tried using older versions of prism yesterday, and it wouldn't work passed version `0.17.1`. The error message is different though, as it doesn't instruct me to do anything, unlike OP where they were told to install the development tools. Should I open a new issue for this?
