### ISSUE TITLE
[COMPILER] Crash in ensure blocks

### ISSUE THREAD

**Issue by peterzhu2118** [ruby/prism#2179]
```ruby
begin
  raise
ensure
end
```

Crashes with:

```
<compiled>:1: [BUG] Segmentation fault at 0x0000000918008080
ruby 3.4.0dev (2024-01-15T16:27:31Z master cc7b19e048) [arm64-darwin23]

-- Crash Report log information --------------------------------------------
   See Crash Report log file in one of the following locations:             
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0004 p:0000 s:4294967312 e:000016 TOP    <compiled>:1 [FINISH]
c:0003 p:---- s:0014 e:000013 CFUNC  :eval
c:0002 p:0061 s:0010 E:0003d8 EVAL   ../test.rb:35 [FINISH]
c:0001 p:0000 s:0003 E:0022b0 DUMMY  [FINISH]

-- Ruby level backtrace information ----------------------------------------
../test.rb:35:in `<main>'
../test.rb:35:in `eval'
<compiled>:1:in `<compiled>'

-- Threading information ---------------------------------------------------
Total ractor count: 1
Ruby thread count for this ractor: 1

-- Machine register context ------------------------------------------------
  x0: 0x00000001217040d0  x1: 0x0000000000000006  x2: 0x00000001010db388
  x3: 0x0000000000000000  x4: 0x0000000008d5a2c0  x5: 0x0000000000000065
  x6: 0x0000000100f5cde0  x7: 0x00000001010db888 x18: 0x0000000000000000
 x19: 0x00000001217040d0 x20: 0x00000001010db388 x21: 0x0000000118107f20
 x22: 0x0000000918008080 x23: 0x000000007fff0001 x24: 0x00000001010dbf90
 x25: 0x0000000000000004 x26: 0x0000000000000024 x27: 0x0000000055550001
 x28: 0x0000000100cecf30  lr: 0x0000000100b5f7e8  fp: 0x000000016f4d29d0
  sp: 0x000000016f4d2920

-- C level backtrace information -------------------------------------------
/Users/peter/src/ruby/build/miniruby(rb_vm_bugreport+0xb4c) [0x100b89d38] ../vm_dump.c:1151
/Users/peter/src/ruby/build/miniruby(rb_vm_bugreport) (null):0
/Users/peter/src/ruby/build/miniruby(rb_bug_for_fatal_signal+0x100) [0x1009cb760] ../error.c:1065
/Users/peter/src/ruby/build/miniruby(sig_do_nothing+0x0) [0x100af16c8] ../signal.c:926
/Users/peter/src/ruby/build/miniruby(sigsegv) (null):0
/usr/lib/system/libsystem_platform.dylib(_sigtramp+0x38) [0x181571a24]
/Users/peter/src/ruby/build/miniruby(vm_exec_loop+0x14) [0x100b5f7e8] ../vm.c:2510
/Users/peter/src/ruby/build/miniruby(rb_vm_exec) ../vm.c:2493
/Users/peter/src/ruby/build/miniruby(vm_exec_loop+0x14) [0x100b5f7e8] ../vm.c:2510
/Users/peter/src/ruby/build/miniruby(rb_vm_exec) ../vm.c:2493
/Users/peter/src/ruby/build/miniruby(vm_call_cfunc_with_frame_+0xf0) [0x100b7cb28] ../vm_insnhelper.c:3492
/Users/peter/src/ruby/build/miniruby(vm_sendish+0xcc) [0x100b62864] ../vm_insnhelper.c:5583
/Users/peter/src/ruby/build/miniruby(vm_exec_core) ../insns.def:834
/Users/peter/src/ruby/build/miniruby(rb_vm_exec+0x1ec) [0x100b5f6a0] ../vm.c:2487
/Users/peter/src/ruby/build/miniruby(rb_ec_exec_node+0xa0) [0x1009d6304] ../eval.c:287
/Users/peter/src/ruby/build/miniruby(ruby_run_node+0x60) [0x1009d61fc] ../eval.c:328
/Users/peter/src/ruby/build/miniruby(rb_main+0x1c) [0x10092ed18] ../main.c:39
/Users/peter/src/ruby/build/miniruby(main) ../main.c:58
```

**Comment by peterzhu2118** [comment]
Potentially related to #2176.
