### ISSUE TITLE
Bug: Prism::Translation::Parser breaks on numbered block params

### ISSUE THREAD

**Issue by exterm** [ruby/prism#2345]
Minimal example:

`Prism::Translation::Parser.parse("find { _1 }")`

fails with "undefined method `parameters' for @ NumberedParametersNode":

```
/home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/translation/parser/compiler.rb:1752:in `visit_block': undefined method `parameters' for @ NumberedParametersNode (location: (1,5)-(1,11)) (NoMethodError)
└── maximum: 1
:Prism::NumberedParametersNode

              block.body&.accept(copy_compiler(forwarding: find_forwarding(block.parameters&.parameters))),
                                                                                           ^^^^^^^^^^^^
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/translation/parser/compiler.rb:244:in `visit_call_node'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/node.rb:2302:in `accept'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/compiler.rb:34:in `block in visit_all'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/compiler.rb:34:in `map'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/compiler.rb:34:in `visit_all'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/translation/parser/compiler.rb:1465:in `visit_statements_node'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/node.rb:16059:in `accept'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/compiler.rb:29:in `visit'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/translation/parser/compiler.rb:1289:in `visit_program_node'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/node.rb:14140:in `accept'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/translation/parser.rb:132:in `build_ast'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/prism-0.20.0/lib/prism/translation/parser.rb:47:in `parse'
	from /home/philip/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.2.2.0/lib/parser/base.rb:33:in `parse'
```

Detected when trying to swap `Prism::Translation::Parser` in for whitequark's `Parser::CurrentRuby` in [packwerk](https://github.com/Shopify/packwerk/pull/388).

**Comment by exterm** [comment]
cc @kddnewton

**Comment by kddnewton** [comment]
Thanks @exterm! Fix is up
