### ISSUE TITLE
$-ßzÉ is considered valid by Prism but not by parse.y

### ISSUE THREAD

**Issue by eregon** [ruby/prism#3129]
I wrote a very naive fuzzer to search for code for which parse.y and Prism differ in whether it's valid Ruby code or not (SyntaxError):

```ruby
puts RUBY_DESCRIPTION
puts RbConfig.ruby

N = Integer(ARGV[0])

require 'prism'

chars = (0...256).map { it.chr(Encoding::UTF_8) }

length = 5

N.times do
  code = length.times.map { chars.sample }.join
  p code

  parse_y_error = false
  begin
    r = RubyVM::AbstractSyntaxTree.parse(code)
    raise unless r
  rescue SyntaxError
    parse_y_error = true
  end
  
  r = Prism.parse(code)
  raise unless r
  prism_error = !r.success?
  
  unless prism_error == parse_y_error
    if prism_error
      raise "Prism raised SyntaxError for #{code.inspect} but parse.y didn't"
    else
      raise "parse.y raised SyntaxError for #{code.inspect} but Prism didn't"
    end
  end
end
```

Running this on ruby-head a couple times I got these failures:
```
"$-ÅÜß"
fuzz.rb:32:in 'block in <main>': parse.y raised for "$-ÅÜß" but Prism didn't (RuntimeError)
...
"$-Ëc\u0092"
fuzz.rb:32:in 'block in <main>': parse.y raised for "$-Ëc\u0092" but Prism didn't (RuntimeError)
...
"$-ßzÉ"
fuzz.rb:32:in 'block in <main>': parse.y raised for "$-ßzÉ" but Prism didn't (RuntimeError)
```
which all seem the same case.

And some more which might be related:
```
fuzz.rb:32:in 'block in <main>': parse.y raised SyntaxError for "y$-öc" but Prism didn't (RuntimeError)
fuzz.rb:32:in 'block in <main>': parse.y raised SyntaxError for "c$-ía" but Prism didn't (RuntimeError)
fuzz.rb:32:in 'block in <main>': parse.y raised SyntaxError for "Õ$-Aö" but Prism didn't (RuntimeError)
fuzz.rb:32:in 'block in <main>': parse.y raised SyntaxError for "±$-å\u008F" but Prism didn't (RuntimeError)
```

**Comment by kddnewton** [comment]
This appeared to be entirely because I thought `$-x` could have multiple characters instead of just 1. The only other errors I could find using your script had to do with parsing regular expressions.

**Comment by eregon** [comment]
> The only other errors I could find using your script had to do with parsing regular expressions.

Should that be fixed as well or is it an intentional difference?

From [the above](https://github.com/ruby/prism/issues/3129#issuecomment-2389752828), removing the `$-` we are left with:
```
parse.y raised SyntaxError for "/é[Â/" but Prism didn't
parse.y raised SyntaxError for "-C\t*É" but Prism didn't
parse.y raised SyntaxError for "~ì\v*Å" but Prism didn't
parse.y raised SyntaxError for "~_\f*÷" but Prism didn't
parse.y raised SyntaxError for "\u0081\rR?:" but Prism didn't
parse.y raised SyntaxError for "-\u0088\v*Ñ" but Prism didn't
parse.y raised SyntaxError for "+\u008D\v*f" but Prism didn't
parse.y raised SyntaxError for "/[°Ý/" but Prism didn't
parse.y raised SyntaxError for "¿Ú>?\\" but Prism didn't
parse.y raised SyntaxError for "ÈQ|?\\" but Prism didn't
```
I think only 2 of them are related to regexps.

Another run with the latest fixes gave:
```
$ ruby fuzz.rb 10000000
ruby 3.4.0dev (2024-10-03T17:43:11Z master 568511f393) +PRISM [x86_64-linux]
/home/eregon/.rubies/ruby-dev/bin/ruby
parse.y raised SyntaxError for "Z½*?\\" but Prism didn't
parse.y raised SyntaxError for "ò«~?\\" but Prism didn't
parse.y raised SyntaxError for "+r\r*k" but Prism didn't
parse.y raised SyntaxError for "\u0090Å~?\\" but Prism didn't
parse.y raised SyntaxError for "~Ù\r*\u0084" but Prism didn't
parse.y raised SyntaxError for "+Ì *É" but Prism didn't
parse.y raised SyntaxError for "-æ\t*\u0089" but Prism didn't
parse.y raised SyntaxError for "-\u0096\f*H" but Prism didn't
parse.y raised SyntaxError for "/[u¹/" but Prism didn't
parse.y raised SyntaxError for "o\u0094-?\\" but Prism didn't
parse.y raised SyntaxError for "E?F!:" but Prism didn't
parse.y raised SyntaxError for "âÆ=?\\" but Prism didn't
parse.y raised SyntaxError for "/¼\u0018[/" but Prism didn't
parse.y raised SyntaxError for "/[O/x" but Prism didn't
parse.y raised SyntaxError for "+\u009D\r*i" but Prism didn't
parse.y raised SyntaxError for "/\\\u0085)/" but Prism didn't
```

Should I open new issue(s) for these ones?
I'm not sure how to group except regexp vs not

**Comment by kddnewton** [comment]
Hmm, I switched it from `RubyVM::AbstractSyntaxTree.parse` to `RubyVM::InstructionSequence.compile` when I did this. I think that got rid of the others.

**Comment by kddnewton** [comment]
I wonder if it's to do with the escaping? All of the examples you have that aren't regexp include escaping.

As for the others — yeah there are some things we won't detect as errors because we rely on the various implementations to give us regexp errors. I want to enhance this eventually, but it's going to take some time.
