### ISSUE TITLE
Unable to install on Windows, Ruby 3.3

### ISSUE THREAD

**Issue by thomthom** [ruby/prism#3323]
I'm using Ruby 3.2 on Windows installed via RubyInstaller. (With DevKit).

I'm getting errors on both my Window system when I try `gem install prism`:

```
C:\Ruby32-x64\bin>gem install prism
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing prism:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/prism-1.2.0/ext/prism
C:/Ruby32-x64/bin/ruby.exe extconf.rb
checking for prism.h in C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/prism-1.2.0/include... yes
checking for prism/extension.h in C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/prism-1.2.0/ext... yes
checking for whether -fvisibility=hidden is accepted as CFLAGS... yes
compiling build/static/diagnostic.o
In function 'pm_diagnostic_message',
    inlined from 'pm_diagnostic_list_append' at src/diagnostic.c:773:20:
src/diagnostic.c:749:46: error: array subscript 319 is above array bounds of 'const pm_diagnostic_data_t[319]' [-Werror=array-bounds]
  749 |     const char *message = diagnostic_messages[diag_id].message;
      |                           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
src/diagnostic.c: In function 'pm_diagnostic_list_append':
src/diagnostic.c:85:35: note: while referencing 'diagnostic_messages'
   85 | static const pm_diagnostic_data_t diagnostic_messages[PM_DIAGNOSTIC_ID_MAX] = {
      |                                   ^~~~~~~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
make: *** [Makefile:58: build/static/diagnostic.o] Error 1
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby32-x64/bin/$(RUBY_BASE_NAME)
        --enable-build-debug
        --disable-build-debug
        --enable-build-minimal
        --disable-build-minimal
extconf.rb:51:in `system': Command failed with exit 2: make (RuntimeError)
        from extconf.rb:51:in `block in make'
        from extconf.rb:50:in `chdir'
        from extconf.rb:50:in `make'
        from extconf.rb:136:in `<main>'
Running make build/libprism.a with {"SOEXT"=>"dll", "MAKEDIRS"=>"/usr/bin/mkdir -p", "RMALL"=>"rm -fr"}

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby32-x64/lib/ruby/gems/3.2.0/extensions/x64-mingw-ucrt/3.2.0/prism-1.2.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/prism-1.2.0 for inspection.
Results logged to C:/Ruby32-x64/lib/ruby/gems/3.2.0/extensions/x64-mingw-ucrt/3.2.0/prism-1.2.0/gem_make.out
```

The content of `C:/Ruby32-x64/lib/ruby/gems/3.2.0/extensions/x64-mingw-ucrt/3.2.0/prism-1.2.0/mkmf.log`:
(PATH stripped from log to make it easier to read)
```
C:\Ruby32-x64\bin>cat C:/Ruby32-x64/lib/ruby/gems/3.2.0/extensions/x64-mingw-ucrt/3.2.0/prism-1.2.0/mkmf.log
find_header: checking for prism.h in C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/prism-1.2.0/include... -------------------- yes

PATH="..."
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return !!argv[argc];
8: }
/* end */

PATH="..."
conftest.c:5:10: fatal error: prism.h: No such file or directory
    5 | #include <prism.h>
      |          ^~~~~~~~~
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <prism.h>
/* end */

PATH="..."
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <prism.h>
/* end */

--------------------

find_header: checking for prism/extension.h in C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/prism-1.2.0/ext... -------------------- yes

PATH="..."
conftest.c:5:10: fatal error: prism/extension.h: No such file or directory
    5 | #include <prism/extension.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <prism/extension.h>
/* end */

PATH="..."
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <prism/extension.h>
/* end */

--------------------

block in append_cflags: checking for whether -fvisibility=hidden is accepted as CFLAGS... -------------------- yes

PATH="..."
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return !!argv[argc];
8: }
/* end */

--------------------
```

**Comment by kddnewton** [comment]
This should be fixed in the next release, because we've changed how the gem is built from extconf.
